/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutRegisteredImport } from './routes/_layout/_registered'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as LayoutRegisteredProfileIndexImport } from './routes/_layout/_registered/profile/index'
import { Route as LayoutRegisteredDashboardIndexImport } from './routes/_layout/_registered/dashboard/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRegisteredRoute = LayoutRegisteredImport.update({
  id: '/_registered',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRegisteredProfileIndexRoute =
  LayoutRegisteredProfileIndexImport.update({
    path: '/profile/',
    getParentRoute: () => LayoutRegisteredRoute,
  } as any)

const LayoutRegisteredDashboardIndexRoute =
  LayoutRegisteredDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => LayoutRegisteredRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_registered': {
      preLoaderRoute: typeof LayoutRegisteredImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/auth/': {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login/': {
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_registered/dashboard/': {
      preLoaderRoute: typeof LayoutRegisteredDashboardIndexImport
      parentRoute: typeof LayoutRegisteredImport
    }
    '/_layout/_registered/profile/': {
      preLoaderRoute: typeof LayoutRegisteredProfileIndexImport
      parentRoute: typeof LayoutRegisteredImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutRegisteredRoute.addChildren([
      LayoutRegisteredDashboardIndexRoute,
      LayoutRegisteredProfileIndexRoute,
    ]),
    LayoutIndexRoute,
  ]),
  AuthIndexRoute,
  AuthLoginIndexRoute,
])

/* prettier-ignore-end */
